### ISSUE TITLE
Indent guides are not being added in Atom 0.206.0

### ISSUE THREAD

**Issue by forsenonlhaimaisentito** [harai/indent-guide-improved#12]
As stated in the title, indent guides are not being added; I've tried to switch to default theme, disable and re-enable the plugin and restart Atom, but still no element or class is being added to the editor's HTML code, built-in guides are disabled and no errors are being shown, it's as if the plugin isn't even there...
The error persists even on a new, default-configured installation of Atom.

I'm using Atom 0.206.0 on 64-bit Linux, package version is the latest (1.2.0).

**Comment by MethodGrab** [comment]
+1, this happened for me as well when I updated from Atom 0.205.0 --> 0.206.0 (OSX 10.10).

**Comment by mike** [comment]
+1, this package stopped working for me recently too :cry: 

I'm currently on Atom 0.207.0 (OSX 10.10), but I believe it stopped working as of 0.206.0, and like mentioned above I also never got any deprecation warnings for this package either.
