### ISSUE TITLE
Guides Ignore Horizontal Scroll Position

### ISSUE THREAD

**Issue by MethodGrab** [harai/indent-guide-improved#14]
Atom v2.0.7
indent-guide-improved v1.2.1

If you have content that overflows the screen, causing horizontal scrollbars, the guides stay in the same position when you scroll horizontally.

Expected behaviour would be the guides remain static in the document, like the built-in guides and earlier versions of this plugin.

![screen shot 2015-06-10 at 2 28 58 pm](https://cloud.githubusercontent.com/assets/2421069/8083546/5d0d5f2c-0f7d-11e5-97c2-5cc740211680.png)
![screen shot 2015-06-10 at 2 28 51 pm](https://cloud.githubusercontent.com/assets/2421069/8083547/5fe04426-0f7d-11e5-9120-30220671090d.png)

**Comment by harai** [comment]
Supported in 1264e82bf5684f7f9bd081d5f244489220950db0.

**Comment by MethodGrab** [comment]
Great, thanks! :metal:
