### ISSUE TITLE
Active guide swallows cursor

### ISSUE THREAD

**Issue by polarathene** [harai/indent-guide-improved#19]
If my cursor moves to an empty line it jumps to the indent guide, unfortunately the cursor seems to be the same white value as the highlighted active guide. Any plans to work around this collision or is that placed on the theme developers to handle?

**Comment by harai** [comment]
The color of indent guides is customizable using [Stylesheet](https://atom.io/docs/v1.0.7/using-atom-basic-customization#style-tweaks).

Copy and paste the following code into it and change as you wish:

```
.indent-guide-improved {
  background-color: gray;
  &.indent-guide-stack {
    background-color: cyan;
    &.indent-guide-active {
      background-color: blue;
    }
  }
}
```

**Comment by polarathene** [comment]
@harai I've tried the following, the color of the indent guides change as expected, however the cursor appears to be covered by the guide? Instead of seeing my white cursor overlayed on top of the guide I instead only see the guide, presumably the cursor is beneath it.

**Comment by polarathene** [comment]
I've just updated my package to 1.4.3 and applied the CSS snippet supplied above, the blinking white cursor is still hidden by the blue indent when I tested. Assuming it works properly on your end? Suggestions?

**Comment by polarathene** [comment]
I've since closed/reopened Atom and that seems to have corrected it. Cheers for the fix :)
