### ISSUE TITLE
Please check "Use Shadow DOM" in Settings.

### ISSUE THREAD

**Issue by lexicalunit** [harai/indent-guide-improved#48]
In what Settings? The Settings for this package? The Setting for Atom Core? The Setting for Atom Editor, Keybindings, Themes? I can't find any setting for "Use Shadow DOM" in any of the above settings locations.

**Comment by lexicalunit** [comment]
Ah, found it. `editor.useShadowDOM` in your `config.cson`. This setting does not appear to be exposed in Atom `1.11.0-beta`.

**Comment by harai** [comment]
#47 should fix this problem.

**Comment by mark-a-dev** [comment]
I don't see this anywhere
