### ISSUE TITLE
Doesn't work on the current 1.13.x beta

### ISSUE THREAD

**Issue by dflock** [harai/indent-guide-improved#51]
Looks like this:

![image](https://cloud.githubusercontent.com/assets/47756/20284310/6b060f08-aa71-11e6-9a15-2700c534892c.png)

Might be something to do with this: https://github.com/atom/atom/pull/12903 ?

**Comment by lexicalunit** [comment]
Seeing the same thing on `1.13.0-beta2`:

<img width="510" alt="screen shot 2016-11-15 at 3 23 33 pm" src="https://cloud.githubusercontent.com/assets/1903876/20324853/d433a0e0-ab47-11e6-9400-4d74e568516c.png">

**Comment by harai** [comment]
atom/atom#12903 introduced this problem.

**Comment by harai** [comment]
I've fixed the problem.  Thanks everyone (especially @dflock ) for reporting!
