### ISSUE TITLE
Package will not work in Atom 1.12 due to shadow DOM setting

### ISSUE THREAD

**Issue by thom801** [harai/indent-guide-improved#56]
I keep getting a notification that I need to enable shadow DOM in settings, but in v1.12 (latest stable release) that version has no shadow DOM checkbox in settings. I think they have removed it from the settings. Normal indent guides work, but when this package is installed they disappear and I keep getting the shadow DOM notification.

**Comment by davidtaylorjr** [comment]
I am also not able to find Shadow DOM

**Comment by davidtaylorjr** [comment]
This is fixed by #48 and should be closed @thom801
