### ISSUE TITLE
Styling for displaying properly

### ISSUE THREAD

**Issue by plttn** [harai/indent-guide-improved#8]
What are the classes you're using? My custom theme isn't showing the highlights on the active guides.

**Comment by harai** [comment]
The css class which applies to all guides is `.indent-guide-improved`.  In addition, `.indent-guide-stack` class is added for stacked guides.  Moreover, if the guide is rightmost, `.indent-guide-active` is also added.

Therefore, if the guide is rightmost, `.indent-guide-improved`, `.indent-guide-stack`, and `.indent-guide-active` are applied.
