### ISSUE TITLE
Disable default indent guide

### ISSUE THREAD

**Issue by simurai** [harai/indent-guide-improved#9]
There are probably a few people that don't read about `Switch off "Show Indent Guide"` in the README. So the idea came up in this discussion https://discuss.atom.io/t/having-a-bit-of-a-issue-with-a-theme-i-converted/16751to disable it when a user installs this package. And maybe show a notification?

It might be controversial changing the user's settings, but in this case maybe ok?

**Comment by harai** [comment]
Thanks for the feedback.
I fixed the issue and released the new version.
